# The URL the site will be built for
base_url = "https://rubenjr0.eu"
title = "rubenjr0"
theme = "kita"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
generate_feeds = true

taxonomies = [
    { name = "category", paginate_by = 5, feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "material-dark"

[extra]
[[extra.menu]]
name = "Projects"
url = "$BASE_URL/projects"

[[extra.menu]]
name = "Resume"
url = "$BASE_URL/resume.pdf"

[[extra.menu]]
name = "Publications"
url = "$BASE_URL/publications"

[[extra.menu]]
name = "Blog"
url = "$BASE_URL/blog"

[[extra.menu]]
name = "About"
url = "$BASE_URL/about"

[extra.style]
bg_dark_color = "#100f0f"
header_blur = true

[extra.profile]
name = "rubenjr0"
bio = "Programming Languages - Machine Learning - Computer Science"
# The URL of avatar.
# avatar_url = "fractal.png"
# Invert color in dark mode.
# avatar_invert = true

[[extra.profile.social]]
name = "github"
url = "https://github.com/rubenjr0"

[[extra.profile.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/rubenjr0"

[[extra.profile.social]]
name = "email"
url = "mailto:rubenjr0@proton.me"

[[extra.profile.social]]
name = "rss"
url = "$BASE_URL/atom.xml"
